<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CC-FRAMEWORK</title>
    <link rel="shortcut icon" href="/public/assets/img/favicon.ico" />
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Rowdies:wght@300&display=swap');
        .container{
            font-family: 'Rowdies', cursive;
            margin: 20px auto;
            width: 100%;
            display: flex;
            align-items: center;
            height: 94vh;
        }
        .title{
            color: tomato;
            font-size: 50px;
        }
        .desc{
            color: #aaa;
            font-size: 40px
        }
        .center{
            width: 100%;
        }
        .text-center{
            text-align: center;
        }
        
    </style>
</head>
<body>
    <div class="container text-center">
        <div class="center">
            <h1 class="title">Página não encontrada!</h1>
            <h4 class="desc">Por favor, verifique se a URL informada está correta.</h4>
        </div>
    </div>
</body>
</html>